version: '3'
services:
  pets_test:
    image: postgres:14.3
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: pets_test
      POSTGRES_USER: u_p
      POSTGRES_PASSWORD: secret12345
    container_name: pets_test
